variables:
  packagePath: '$(System.DefaultWorkingDirectory)/src.zip'
  azureSubscription: 'AuthDevOps'
  functionAppName: 'DevOpsauth32'
  resourceGroupName: 'DevOpsauth32_group'
  
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    cd js
    npm install
  displayName: 'Install dependencies'

- script: |
    cd js
    zip -r ../src.zip .
  displayName: 'Zip Function App'

- task: AzureFunctionApp@1
  inputs:
    azureSubscription: $(azureSubscription)
    appType: 'functionApp'
    appName: $(functionAppName)
    resourceGroupName: $(resourceGroupName)
    package: $(packagePath)
    enableManagedIdentity: true
    deploymentMethod: 'zipDeploy'
